# There are 3 things in thie file that may need updating from the user, all based off the information in the NGC model tag
# This model comes from https://registry.ngc.nvidia.com/orgs/ohlfw0olaadg/teams/ea-participants/models/llama-2-7b with latest tag 'LLAMA-2-7B-4K-FP16-1-A100.24.01'
# Based on this tag, the model requires 1-A100 gpu and the NIM runtime version is 24.01, these values must be set below if a different model version was downloaded.
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama2-7b-chat-1xgpu-day0
  annotations:
    model_dir: "Llama-2-7b-chat-hf" # Name of directory model is stored in, required for day0
    num_gpus: "1" # The number of GPUs for this model, passed to startup script, do not change
    ngc_model_location: "hf.co:meta-llama/Llama-2-7b-chat-hf" # Currently stored for reference
    nim_model_name: "llama2-7b-chat" # The name used when making API calls into the model
    autoscaling.knative.dev/target: "10" # Enable auto-scaling, set max queue size to 10 per NIM Pod
spec:
  predictor:
    minReplicas: 1 # Set to 0 to enable scale-to-zero
    model:
      modelFormat:
        name: nvidia-nim-llm 
      # INFO: Update the 'nim-pvc' value to the name of the PVC created
      # This path is dependant on the format of the model from NGC, it is the result of fully unpacking any tarball after downloading the NGC or HF artifact
      # This assumes all models are downloaded into pvc://<pvc-name>/model-store/<model-specific-structure>
      storageUri: "pvc://nim-pvc/model-store/Llama-2-7b-chat-hf/"
      runtime: nvidia-nim-llm-24.02.day0
      resources:
        limits:
          nvidia.com/gpu: 1
        requests:
          nvidia.com/gpu: 1
